quarkus.devservices.enabled=false
kogito.devservices.enabled=false

# NOTE: the dev profile can be used for local execution, and is not enabled when building the image.
%dev.kogito.service.url=http://localhost:8080
%dev.kafka.bootstrap.servers=localhost:9092
# Prevent the WF to try to communicate with the Data Index and Jobs Service if executed locally.
%dev.kogito.events.usertasks.enabled=false
%dev.kogito.events.variables.enabled=false
%dev.kogito.events.processinstances.enabled=false
%dev.kogito.events.processdefinitions.enabled=false

# NOTE: The tls profile is for local execution and testing, and is not enabled when building the image.
%tls.mp.messaging.connector.smallrye-kafka.security.protocol=SSL
# Specify the enabled TLS protocols (forcing TLSv1.2)
%tls.mp.messaging.connector.smallrye-kafka.ssl.enabled.protocols=TLSv1.2

# Truststore configuration (so the client can validate the broker's certificate)
%tls.mp.messaging.connector.smallrye-kafka.ssl.truststore.location=/deployment/certs/kafka.truststore.jks
%tls.mp.messaging.connector.smallrye-kafka.ssl.truststore.password=kafka-pass

######################################################################
# Workflow Kafka events configuration (Important!)
######################################################################
# Build time configuration, all workflow business events sent / or received via kafka, must have the respective
# outgoing (or incoming) connector defined, including the topic name, or any other additional related configuration
# used by Quarkus to construct the connector. Thinks like, keystore, truststore, can be run time configurations.
mp.messaging.incoming.start_event.connector=smallrye-kafka
mp.messaging.incoming.start_event.topic=start-event
mp.messaging.incoming.start_event.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.exit_event.connector=smallrye-kafka
mp.messaging.outgoing.exit_event.topic=exit-event
mp.messaging.outgoing.exit_event.value.serializer=org.apache.kafka.common.serialization.StringSerializer

######################################################################
# End of Workflow Kafka events configuration
######################################################################
